name: python-template
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.08.22=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=1.1.1v=h2bbff1b_0
  - pip=23.2.1=py310haa95532_0
  - python=3.10.9=h966fe2a_2
  - setuptools=68.0.0=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - flipside==2.0.8
      - idna==3.4
      - numpy==1.25.2
      - pandas==2.1.0
      - plotly==5.16.1
      - pydantic==1.10.9
      - pytz==2023.3.post1
      - requests==2.29.0
      - tenacity==8.2.3
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==1.26.16
prefix: C:\Users\crmer\miniconda3\envs\python-template
